#include "generator/main.h"
#include "test/quick-sort.h"

/**
 * @brief Outputs an array of integers to a specific file.
 *
 * @param filename The path to the file. If using a relative path, make sure it is relative
 * to the folder "build" within the project.
 * @param data An array of integers that we wish to print to the file.
 * @param length The number of integers that we wish to print to the file.
 */
void generate_file(const char *filename, int data[], size_t length)
{
    FILE *f = fopen(filename, "w+");

    for (int i = 0; i < length; i++)
    {
        fprintf(f, "%d%s", data[i], i != length - 1 ? DELIMITER : "");
    }

    fclose(f);
}

/**
 * @brief If the directory does not exist we will generate the directory
 *
 * @param directory the directory we plan on creating
 */
void generate_directory(const char *directory)
{
    struct stat st = {0};
    if (stat(directory, &st) == -1)
    {
        mkdir(directory, 0777);
    }
}

/**
 * @brief Generates a list of random numbers
 *
 * @param length number of random numbers needed to be generated
 * @return int* the data generated by the random method
 */
int *generate_random_data(int length)
{
    int *data = (int *)calloc(length, sizeof(int));
    for (int i = 0; i < length; i++)
    {
        data[i] = rand() % (MAX_INT - MIN_INT) + MIN_INT;
    }

    return data;
}

/**
 * @brief Generates a set of data then sorts it.
 *
 * @param length The number of elements we want to generate.
 * @return int* The set of data that we generated
 */
int *generate_sorted_data(int length)
{
    int *data = generate_random_data(length);
    quick_sort(data, length);

    return data;
}

/**
 * @brief Generates a sorted list, then reverses it
 *
 * @param length The length of the array
 * @return int* The resulting array of reverse sorted data.
 */
int *generate_reverse_sorted_data(int length)
{
    int *data = generate_sorted_data(length);

    int start = 0;
    int end = length - 1;

    int temp;
    while (start < end)
    {
        temp = data[start];
        data[start] = data[end];
        data[end] = temp;

        start++;
        end--;
    }

    return data;
}

/**
 * @brief Generates all of the data and populates the files.
 */
void GenerateData()
{
    // Initialize the random seed with the current time
    srand(time(0));

    char *base = "../data/";
    char path[256];

    char *sections[] = {"unsorted", "sorted", "reverse-sorted"};
    int *(*functions[3])(int) = {generate_random_data, generate_sorted_data, generate_reverse_sorted_data};

    char *sizes[] = {"small", "medium", "large"};
    int size_nums[] = {10000, 100000, 1000000};

    time_t begin_time = clock();

    generate_directory("../data");
    for (int i = 0; i < 3; i++)
    {
        char base[256] = "../data/";
        generate_directory(strcat(base, sections[i]));

        for (int j = 0; j < 3; j++)
        {
            char base2[256] = "../data/";
            generate_directory(strcat(strcat(strcat(base2, sections[i]), "/"), sizes[j]));

            for (int k = 1; k <= 30; k++)
            {
                int *data = functions[i](size_nums[j]);
                sprintf(path, "../data/%s/%s/%d.txt", sections[i], sizes[j], k);
                generate_file(path, data, size_nums[j]);

                free(data);
            }
        }
    }

    time_t end_time = clock();
    double time_difference = (double)(end_time - begin_time) / CLOCKS_PER_SEC;

    printf("Generated all data in: %f seconds\n", time_difference);
}